<?php

namespace PhotoBlogBundle\Repository;

/**
 * PhotoPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoPostRepository extends \Doctrine\ORM\EntityRepository
{
}
